### ISSUE TITLE
Broken Styles

### ISSUE THREAD

**Issue by ZakariaRidouh** [amilajack/popcorn-desktop-experimental#18]
I cloned the repo and tried to test out the app, but I found that all the styles are broken like so:

![image](https://cloud.githubusercontent.com/assets/11602629/15638273/3c3b30b8-25d3-11e6-87b9-0996aa96daa8.png)
 and 
![image](https://cloud.githubusercontent.com/assets/11602629/15638277/441f4a30-25d3-11e6-8bc9-6f87e620e365.png)

Thanks!

**Comment by amilajack** [comment]
The styles are not broken. This project is a project that was started from scratch.

**Comment by ZakariaRidouh** [comment]
Whoops my bad, I didnt see the screenshots on the README.md titled _goal_. I thought that is what is currently on the app.

On a different note, what are some of the frameworks you plan on using with the app? This one looks quite good: http://www.material-ui.com/#/

**Comment by amilajack** [comment]
I'm currently using bootstrap 4. I don't think that the default theme will have a material look to it. However, I will be using css-variables to allow users to easily configure css values dynamically.
